server:
  port: 8081

spring:
  application:
    name: exchange-rate-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

fx:
  kafka:
    topic: exchange-rate-events
  awesome-api:
    usd-brl-url: https://economia.awesomeapi.com.br/json/last/USD-BRL
  poll:
    api-interval-ms: 60000
    simulation-interval-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
